[package]
name = "zserve"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
bytes = "1.9.0"
clap = { version = "4.5.23", features = ["derive"] }
env_logger = "0.11.6"
mdns-sd = "0.13.1"
tokio = { version = "1.42.0", features = ["fs", "macros", "net", "rt"] }
tracing = "0.1.41"
